import type { Palette, PaletteSummary } from './types.js';

/**
 * Built-in palettes. These are faithful (as faithful as a diagram allows) to the
 * colour schemes developers already live in, so a themed diagram sits naturally
 * next to the editor it was written in.
 */
export const PALETTES: Record<string, Palette> = {
  dracula: {
    id: 'dracula',
    name: 'Dracula',
    appearance: 'dark',
    bg: '#282a36',
    bgGradient: ['#282a36', '#1e2029'],
    surface: '#343746',
    surfaceAlt: '#2f3241',
    border: '#6272a4',
    text: '#f8f8f2',
    textMuted: '#a1a8c9',
    accent: '#bd93f9',
    edge: '#8a92c4',
    edgeLabelBg: '#383a4c',
    hues: {
      blue: '#6272a4',
      cyan: '#8be9fd',
      green: '#50fa7b',
      yellow: '#f1fa8c',
      orange: '#ffb86c',
      red: '#ff5555',
      purple: '#bd93f9',
      pink: '#ff79c6',
    },
  },
  'one-dark-pro': {
    id: 'one-dark-pro',
    name: 'One Dark Pro',
    appearance: 'dark',
    bg: '#282c34',
    bgGradient: ['#282c34', '#21252b'],
    surface: '#2c313a',
    surfaceAlt: '#31363f',
    border: '#3e4451',
    text: '#abb2bf',
    textMuted: '#7f8794',
    accent: '#61afef',
    edge: '#5c6370',
    edgeLabelBg: '#313640',
    hues: {
      blue: '#61afef',
      cyan: '#56b6c2',
      green: '#98c379',
      yellow: '#e5c07b',
      orange: '#d19a66',
      red: '#e06c75',
      purple: '#c678dd',
      pink: '#e06c75',
    },
  },
  nord: {
    id: 'nord',
    name: 'Nord',
    appearance: 'dark',
    bg: '#2e3440',
    bgGradient: ['#2e3440', '#272c36'],
    surface: '#3b4252',
    surfaceAlt: '#434c5e',
    border: '#4c566a',
    text: '#eceff4',
    textMuted: '#a4aec4',
    accent: '#88c0d0',
    edge: '#677691',
    edgeLabelBg: '#3b4252',
    hues: {
      blue: '#81a1c1',
      cyan: '#88c0d0',
      green: '#a3be8c',
      yellow: '#ebcb8b',
      orange: '#d08770',
      red: '#bf616a',
      purple: '#b48ead',
      pink: '#d08770',
    },
  },
  'gruvbox-dark': {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    appearance: 'dark',
    bg: '#282828',
    bgGradient: ['#282828', '#1d2021'],
    surface: '#3c3836',
    surfaceAlt: '#423d3a',
    border: '#504945',
    text: '#ebdbb2',
    textMuted: '#bdae93',
    accent: '#fabd2f',
    edge: '#7c6f64',
    edgeLabelBg: '#3c3836',
    hues: {
      blue: '#83a598',
      cyan: '#8ec07c',
      green: '#b8bb26',
      yellow: '#fabd2f',
      orange: '#fe8019',
      red: '#fb4934',
      purple: '#d3869b',
      pink: '#d3869b',
    },
  },
  'catppuccin-mocha': {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    appearance: 'dark',
    bg: '#1e1e2e',
    bgGradient: ['#1e1e2e', '#181825'],
    surface: '#313244',
    surfaceAlt: '#292c3c',
    border: '#45475a',
    text: '#cdd6f4',
    textMuted: '#a6adc8',
    accent: '#cba6f7',
    edge: '#7f849c',
    edgeLabelBg: '#313244',
    hues: {
      blue: '#89b4fa',
      cyan: '#94e2d5',
      green: '#a6e3a1',
      yellow: '#f9e2af',
      orange: '#fab387',
      red: '#f38ba8',
      purple: '#cba6f7',
      pink: '#f5c2e7',
    },
  },
  'tokyo-night': {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    appearance: 'dark',
    bg: '#1a1b26',
    bgGradient: ['#1a1b26', '#16161e'],
    surface: '#24283b',
    surfaceAlt: '#1f2335',
    border: '#414868',
    text: '#c0caf5',
    textMuted: '#8990b3',
    accent: '#7aa2f7',
    edge: '#565f89',
    edgeLabelBg: '#24283b',
    hues: {
      blue: '#7aa2f7',
      cyan: '#7dcfff',
      green: '#9ece6a',
      yellow: '#e0af68',
      orange: '#ff9e64',
      red: '#f7768e',
      purple: '#bb9af7',
      pink: '#f7768e',
    },
  },
  monokai: {
    id: 'monokai',
    name: 'Monokai',
    appearance: 'dark',
    bg: '#272822',
    bgGradient: ['#272822', '#1f201b'],
    surface: '#34352f',
    surfaceAlt: '#3b3c35',
    border: '#49483e',
    text: '#f8f8f2',
    textMuted: '#b3b1a3',
    accent: '#a6e22e',
    edge: '#75715e',
    edgeLabelBg: '#34352f',
    hues: {
      blue: '#66d9ef',
      cyan: '#66d9ef',
      green: '#a6e22e',
      yellow: '#e6db74',
      orange: '#fd971f',
      red: '#f92672',
      purple: '#ae81ff',
      pink: '#f92672',
    },
  },
  'rose-pine': {
    id: 'rose-pine',
    name: 'Rosé Pine',
    appearance: 'dark',
    bg: '#191724',
    bgGradient: ['#191724', '#14131f'],
    surface: '#1f1d2e',
    surfaceAlt: '#26233a',
    border: '#403d52',
    text: '#e0def4',
    textMuted: '#a9a4c0',
    accent: '#c4a7e7',
    edge: '#6e6a86',
    edgeLabelBg: '#26233a',
    hues: {
      blue: '#9ccfd8',
      cyan: '#9ccfd8',
      green: '#31748f',
      yellow: '#f6c177',
      orange: '#ebbcba',
      red: '#eb6f92',
      purple: '#c4a7e7',
      pink: '#eb6f92',
    },
  },
  'github-light': {
    id: 'github-light',
    name: 'GitHub Light',
    appearance: 'light',
    bg: '#ffffff',
    bgGradient: ['#ffffff', '#f6f8fa'],
    surface: '#f6f8fa',
    surfaceAlt: '#eef1f4',
    border: '#d0d7de',
    text: '#1f2328',
    textMuted: '#59636e',
    accent: '#0969da',
    edge: '#8c959f',
    edgeLabelBg: '#eef1f4',
    hues: {
      blue: '#0969da',
      cyan: '#1b7c83',
      green: '#1a7f37',
      yellow: '#9a6700',
      orange: '#bc4c00',
      red: '#cf222e',
      purple: '#8250df',
      pink: '#bf3989',
    },
  },
  'solarized-light': {
    id: 'solarized-light',
    name: 'Solarized Light',
    appearance: 'light',
    bg: '#fdf6e3',
    bgGradient: ['#fdf6e3', '#f7f0dc'],
    surface: '#eee8d5',
    surfaceAlt: '#e7e1cd',
    border: '#cdc4ac',
    text: '#073642',
    textMuted: '#657b83',
    accent: '#268bd2',
    edge: '#93a1a1',
    edgeLabelBg: '#eee8d5',
    hues: {
      blue: '#268bd2',
      cyan: '#2aa198',
      green: '#859900',
      yellow: '#b58900',
      orange: '#cb4b16',
      red: '#dc322f',
      purple: '#6c71c4',
      pink: '#d33682',
    },
  },
  'nord-light': {
    id: 'nord-light',
    name: 'Nord Light',
    appearance: 'light',
    bg: '#fbfcfd',
    bgGradient: ['#ffffff', '#eef1f6'],
    surface: '#e9edf3',
    surfaceAlt: '#dfe5ee',
    border: '#c2cad8',
    text: '#2e3440',
    textMuted: '#5a6679',
    accent: '#5e81ac',
    edge: '#94a3bd',
    edgeLabelBg: '#e9edf3',
    hues: {
      blue: '#5e81ac',
      cyan: '#4f8fa6',
      green: '#7d9a63',
      yellow: '#b58a35',
      orange: '#c06a4a',
      red: '#b1474f',
      purple: '#94699a',
      pink: '#bf7483',
    },
  },
};

export const PALETTE_IDS = Object.keys(PALETTES);

export function isPalette(value: unknown): value is Palette {
  if (typeof value !== 'object' || value === null) return false;
  const p = value as Partial<Palette>;
  return typeof p.id === 'string' && typeof p.bg === 'string' && typeof p.surface === 'string';
}

export function getPalette(id: string): Palette | undefined {
  return PALETTES[id] ?? PALETTES[id.toLowerCase()];
}

export function listPalettes(): PaletteSummary[] {
  return Object.values(PALETTES).map((p) => ({
    id: p.id,
    name: p.name,
    appearance: p.appearance,
    accent: p.accent,
    bg: p.bg,
  }));
}

/** Fill in missing fields of a user-supplied palette from a base scheme. */
export function normalizePalette(input: Palette | string): Palette {
  if (typeof input === 'string') {
    const found = getPalette(input);
    if (!found) {
      const available = PALETTE_IDS.join(', ');
      throw new Error(`Unknown palette "${input}". Available palettes: ${available}`);
    }
    return found;
  }
  const base = PALETTES['dracula']!;
  return {
    ...base,
    ...input,
    hues: { ...base.hues, ...(input.hues ?? {}) },
  };
}
